Add Git icons to the GithubEvent card title
coronasafe/leaderboard pull request #232
Opened 2024-02-22 18:19 UTC by dgparmar14

I add icons to the "GithubEvent card title" as per the git hub actions mentioned

2024-02-22 18:39 UTC, rithviknishad requested changes

2024-02-22 18:39 UTC, rithviknishad commented on app/contributors/dgparmar14.md
Discard this file. You can add your markdown to https://github.com/coronasafe/leaderboard-data repo. This repo does not and should not contain any specific data as other organizations would be using this as source code to deploy their data.

2024-02-22 18:39 UTC, rithviknishad commented on contributors
This symlink is required for leaderboard to correctly point to the data source

2024-02-22 18:40 UTC, rithviknishad commented on app/contributors/dgparmar14.md
Tomorrow morning your markdown profile will be auto-generated by the scrapper workflow. You could also simply edit the existing markdown too then.

2024-02-23 06:24 UTC, rithviknishad requested changes

2024-02-23 06:24 UTC, rithviknishad commented on contributors
Still unresolved

2024-02-23 06:35 UTC, dgparmar14 commented
Okay i will do it

2024-02-23 07:22 UTC, closed without merging