Change all anchor and img tag with next?Link and next/Image tags
coronasafe/leaderboard pull request #236
Opened 2024-02-23 17:41 UTC by dgparmar14

# Description
I noticed by the observation that in some files there used anchor tag and img tag. So as we know for enhancement of performance there are features for that next/image and next/link. So, I replace all possible anchor tags with Link tags and all image tage with next/Image tag

Fixes #234 

## Type of change

Change a syntax and in the image tag add a default height and width accordingly.
As per next/Image feature I add hostname of the image provider in the Next.config.js file

# Checklist:
- [ ] I have performed a self-review of my code

2024-02-23 17:42 UTC, dgparmar14 commented
@rithviknishad please review my pr

2024-02-24 03:54 UTC, rithviknishad commented
@dgparmar14 fix the prettier issues

<img width="1284" alt="image" src="https://github.com/coronasafe/leaderboard/assets/25143503/4778f4ab-5e9b-442b-a54f-077a7caa21ab">

2024-02-24 06:26 UTC, dgparmar14 commented
@rithviknishad I removed all eslint errors please review it

2024-02-24 06:46 UTC, rithviknishad requested changes

2024-02-24 06:46 UTC, rithviknishad commented on package-lock.json
Why was `package-lock.json` added? We are having pnpm lock file already.
It'd be nice if you could add this to the `.gitignore` too so other contributors may not accidentally add it too.

2024-02-24 07:02 UTC, dgparmar14 commented on package-lock.json
Sorry, it may be add because of i run on npm . I will add package-lock.josn in .gitignore.
and can you give more detail of above screen shot error

2024-02-24 08:19 UTC, rithviknishad commented on package-lock.json
Could you remove this file from being tracked? Since this was gitignored after it was checked in, git will continue to track it.

https://stackoverflow.com/a/1274447/7887936

2024-02-24 08:41 UTC, dgparmar14 commented
@rithviknishad @gsoc Okay I push all changes as per your instructions

2024-02-24 08:48 UTC, dgparmar14 commented
it will now merged or any changes reuired?
@rithviknishad

2024-02-24 08:50 UTC, rithviknishad requested changes

2024-02-24 08:50 UTC, rithviknishad commented on components/gh_events/ReleaseEventBody.tsx
>              {/* eslint-disable-next-line @next/next/no-img-element */}
```suggestion
```

2024-02-24 08:50 UTC, rithviknishad commented on components/gh_events/OpenGraphImage.tsx
>        {/* eslint-disable-next-line @next/next/no-img-element */}
```suggestion
```

2024-02-24 08:50 UTC, rithviknishad commented on components/gh_events/GitHubEvent.tsx
>              {/* eslint-disable-next-line @next/next/no-img-element */}
```suggestion
```

2024-02-24 08:50 UTC, rithviknishad commented on components/contributors/GraduateAttributeBadge.tsx
>  /* eslint-disable @next/next/no-img-element */
```suggestion
```

2024-02-24 09:11 UTC, dgparmar14 commented
Okk, all done as per your instruction. If still any cahnges please guide me.

2024-02-24 12:05 UTC, dgparmar14 commented
@rithviknishad Can you please review agai.Thank you.

2024-02-24 15:04 UTC, rithviknishad approved these changes

2024-02-24 15:21 UTC, merged