New feature navbar added
coronasafe/leaderboard pull request #266
Opened 2024-02-27 16:20 UTC by dgparmar14

# Description
Here is a Navbar added for our leaderboard page. and it also looks beautiful and also a responsive sidebar for mobile as well. 

Fixes #246

## Type of change
 Nabar added in header.tsx component.
Sidebar for mobile navigation.

2024-02-27 16:21 UTC, dgparmar14 commented
@rithviknishad Hey, Rithvik can you review it?

2024-02-28 03:37 UTC, rithviknishad requested changes

2024-02-28 03:37 UTC, rithviknishad commented on components/gh_events/GitHubEvent.tsx
Why are there changes in GitHubEvent.tsx in this PR?

2024-02-28 04:01 UTC, dgparmar14 commented on components/gh_events/GitHubEvent.tsx
Because there is an issue while creating a navbar for mobile so, that's why I added. I will revert it

2024-02-28 04:57 UTC, closed without merging