chore: allocated types, consts and utility functions to separate files
coronasafe/leaderboard pull request #308
Opened 2024-03-02 14:33 UTC by Re-Dei

## Issue Fixed
#277 

## Changes:
Allocated the constants, types, and utility functions that were exported in the files below to separate files:
- app/api/leaderboard/functions.ts
- app/api/leaderboard/route.ts
- app/leaderboard/_components/Leaderboard.tsx
- app/leaderboard/_components/LeaderboardWrapper.tsx
- app/leaderboard/_components/Searchbar.tsx
- app/leaderboard/page.tsx
-  components/DateRangePicker.tsx
- components/contributors/LeaderboardCard.tsx
- components/contributors/TopContributor.tsx

## Problem solved:
Importing from these files could cause server-side rendering issues so I allocated them to separate files. Also, it has the added benefit of decreasing chunk size as importing from these files imported the react components with themselves.

## Testing:
Tested in both production and development in WSL2.

2024-03-02 14:43 UTC, Re-Dei commented
@rithviknishad please review this PR.
Regarding GSOC, I know it's a bit early but I have a favor to ask. Could you check out my project proposal? Just a few minutes will be fine. I heard it was a common practice to get proposals checked by mentors a few weeks before application period begins. I am sorry if its not the case. If its ok by you, I will dm my google docs link to you in slack. Also in how many projects can each contributor apply? I didn't find any information related to it. I just know each contributor can apply to at most 3 organizations.

2024-03-04 03:53 UTC, rithviknishad requested changes

2024-03-04 03:53 UTC, rithviknishad commented on lib/const.ts
> +};
Add `as const` for all these, so that we can use it in a typesafe manner in other places

2024-03-04 03:53 UTC, rithviknishad commented on lib/types.ts
> +    role?: ("core" | "intern" | "operations" | "contributor")[];
```suggestion
    role?: (keyof typeof FILTER_BY_ROLE_OPTIONS)[];
```

2024-03-04 03:53 UTC, rithviknishad commented on app/leaderboard/_components/Leaderboard.tsx
>  // import { formatDate } from "@/components/DateRangePicker";
```suggestion
```

2024-03-04 11:02 UTC, merged