Directly pushes to leaderboard page with default options
coronasafe/leaderboard pull request #310
Opened 2024-03-03 07:33 UTC by UdaySagar-Git

fixes #289

2024-03-03 11:53 UTC, UdaySagar-Git commented
@rithviknishad should i update home page leader board page with default roles or 
let it be for all roles

2024-03-04 03:20 UTC, rithviknishad requested changes
Also update the home page

2024-03-04 03:20 UTC, rithviknishad commented on app/leaderboard/_components/LeaderboardWrapper.tsx
> +    )[]) ?? deaultRoles.map((i) => i.value),
Let's keep this configurable as different organizations require different behaviour. Move this to the environment: `NEXT_PUBLIC_LEADERBOARD_DEFAULT_ROLES=comma,seperated,values`

2024-03-04 03:20 UTC, rithviknishad commented on lib/const.ts
> +];
Not required once moved to env

2024-03-04 06:19 UTC, UdaySagar-Git commented
@rithviknishad can you please review

2024-03-04 06:30 UTC, rithviknishad approved these changes

2024-03-04 06:32 UTC, merged