Community Engagement Graph/Trendline
coronasafe/leaderboard pull request #335
Opened 2024-03-05 07:59 UTC by kirtanchandak

- fetch data from JSON files regarding pr, issues, comments 
- used Chart.js to display the data into stacked bar chart 

![image](https://github.com/coronasafe/leaderboard/assets/92196705/85aa63f5-59a7-4dde-8d37-ac20090fb7d6)

2024-03-05 08:46 UTC, rithviknishad requested changes

2024-03-13 04:06 UTC, kirtanchandak commented on app/people/page.tsx
> +  });
naming conventions here is causing the issue and the file is becoming too big, should I create a new file in this folder for this specific use case?

2024-03-13 04:08 UTC, rithviknishad commented on app/people/page.tsx
> +  });
yes, but inside `lib` directory

2024-07-25 10:30 UTC, rithviknishad commented
Closing as stale and has conflicts. Feel free to re-open.

2024-07-25 10:30 UTC, closed without merging