Prevents duplicate events from merging with existing events.
coronasafe/leaderboard pull request #341
Opened 2024-03-05 19:59 UTC by UdaySagar-Git

fixes #324  

- Created a script for cleaning up existing data.
- Prevents duplicate events from getting merged.

2024-03-05 20:00 UTC, UdaySagar-Git commented
@rithviknishad can you please review

2024-03-06 11:15 UTC, rithviknishad requested changes
@UdaySagar-Git Although this would work, just thought we could do it more cleanly.

1. Let's use `fs/promises` and `async/await`s instead and parallelize by wrapping the job in a `Promise.all` for each contributor.
2. We could ensure uniqueness using `Object.values(Object.fromEntries(...))` approach in a more cleaner way.

<img width="645" alt="image" src="https://github.com/coronasafe/leaderboard/assets/25143503/66dcc08f-4d6b-4b3b-a486-a599fe304765">

2024-03-06 11:53 UTC, UdaySagar-Git commented
Sure will update shortly

2024-03-06 12:40 UTC, UdaySagar-Git commented
@rithviknishad updated and re ran script for confirmation

2024-03-06 17:22 UTC, rithviknishad approved these changes

2024-03-06 17:25 UTC, merged