fixed -> clicking on commit link on /feed. redirects to GitHub API
coronasafe/leaderboard pull request #351
Opened 2024-03-07 09:29 UTC by manu-r12

The actual problem was that the url to specifc commit was taking to the GitHub API not to the actual html url

2024-03-07 09:39 UTC, rithviknishad requested changes
Deploy failing...

<img width="1325" alt="image" src="https://github.com/coronasafe/leaderboard/assets/25143503/50c42056-9853-47b7-9d1b-707b96ab1112">

2024-03-07 09:39 UTC, rithviknishad commented on components/DateRangePicker.tsx
> +`import React from "react";
I assume this change was accidental?

```suggestion
import React from "react";
```

2024-03-07 09:39 UTC, rithviknishad commented on yarn.lock
Remove this file, we are using pnpm lock file in this repo.

2024-03-07 09:40 UTC, manu-r12 commented on yarn.lock
> Remove this file, we are using pnpm lock file in this repo.

which one?

2024-03-07 10:00 UTC, manu-r12 commented on yarn.lock
Done ✅

2024-03-08 04:53 UTC, manu-r12 commented
@rithviknishad  can you review it now 😃

2024-03-08 04:54 UTC, rithviknishad approved these changes

2024-03-08 04:55 UTC, merged