Replaced fetch with Ocktokit in GitHubEvents
coronasafe/leaderboard pull request #365
Opened 2024-03-10 14:53 UTC by Ashutosh0602

Removed fetch and used Ocktokit to retrieve data from API in `GitHubEvents.tsx` file.

 fix: #346

2024-03-10 14:54 UTC, Ashutosh0602 commented
@rithviknishad I have tried to replace fetch ocktokit is it right?

2024-03-10 16:06 UTC, rithviknishad requested changes

2024-03-10 16:06 UTC, rithviknishad commented on components/gh_events/GitHubEvents.tsx
> +  const response = await octokit.paginate("GET /orgs/{org}/events", {
We only need the first 5 events. This does not require us to paginate as the first page of 100 results would be sufficient.

```suggestion
  const response = await octokit.request("GET /orgs/{org}/events", {
```

2024-03-10 16:06 UTC, rithviknishad commented on components/gh_events/GitHubEvents.tsx
> +async function getEvent() {
```suggestion
async function getEvents() {
```

2024-03-10 16:06 UTC, rithviknishad commented on components/gh_events/GitHubEvents.tsx
> +      .filter(exludeBotEvents as any)
do not use `any` instead try inlining the function so that you can skip defining the types.

2024-03-10 16:06 UTC, rithviknishad commented on components/gh_events/GitHubEvents.tsx
> +  }
Let's not do this here. Ideally, this should be done at by env schema validation at build time and not during rendering. 

```suggestion
```

2024-03-10 16:06 UTC, rithviknishad commented on components/gh_events/GitHubEvents.tsx
> +            <GitHubEvent key={e.id} event={e as IGitHubEvent | undefined} />
just directly pass `e` without casting. If type definition at GitHub event is wrong, change that instead.

2024-03-12 05:39 UTC, Ashutosh0602 commented
@rithviknishad I made the changes have a look

2024-03-12 06:08 UTC, rithviknishad requested changes

2024-03-12 06:08 UTC, rithviknishad commented on components/gh_events/GitHubEvents.tsx
> +  const events = await getEvents().then((res: any) =>
Let's try to not use `any` type.

2024-03-12 16:30 UTC, rithviknishad requested changes
You need to ensure there are no errors before requesting for review. By removing `any` type, I meant to fix the type errors along with it.

<img width="1289" alt="image" src="https://github.com/coronasafe/leaderboard/assets/25143503/16baa5ca-b6cb-433b-93ac-9b6984a820f5">

2024-03-12 16:57 UTC, merged