enable/disable features from env variables
coronasafe/leaderboard pull request #418
Opened 2024-04-01 05:21 UTC by rash-27

- fix #413

2024-04-01 07:16 UTC, rithviknishad requested changes
Can we create a typesafe utility function that can be invoked like this to check the status of the feature flag?

```ts
if (!featureIsEnabled("feature-name")) {
  return notFound();
}
```

2024-04-01 07:21 UTC, rithviknishad commented
> I have considered the env variable as a string with features separated with a ', ', Is that a good practice to do so?

It should be fine for now. We can refactor it later if we encounter an issue with this approach.

> And should I also add checks for the leaderboard and other routes as well?
The leaderboard is always going to be present since all orgs would have some activity where the leaderboard would have data. Let's not disable it...
We can now have flags for routes like "projects" and "releases" for now.

cc: @bodhish

2024-04-01 07:21 UTC, rash-27 commented
Yes , I'll update it

2024-04-01 08:28 UTC, rithviknishad requested changes

2024-04-01 08:28 UTC, rithviknishad commented on lib/utils.ts
> +};
import the typesafe env instead + add typesafety.

```suggestion
type Feature = "releases" | "projects";

export const featureIsEnabled = (feature: Feature) => {
  return env.NEXT_PUBLIC_FEATURES?.split(",").includes(feature);
};
```

2024-04-18 06:17 UTC, rithviknishad requested changes
LGTM, update the README too.

2024-04-18 06:20 UTC, rash-27 commented
Ok sure!

2024-04-19 05:12 UTC, rithviknishad approved these changes

2024-04-19 05:13 UTC, merged