GSoC_Week1_Refactor Github Scrapper
coronasafe/leaderboard pull request #458
Opened 2024-06-06 05:25 UTC by dgparmar14

# Description

**GSoC Week 1:** Refactoring from `github.py` to `github.ts`

This task aims to refactor the existing Python scraper into TypeScript. The transition to TypeScript will enhance the codebase by introducing `type safety` and leveraging the capabilities of `Octokit` for easier GitHub interactions.

**Fixes:** #212

## Type of change

1. Refactor the existing scraper from `github.py` to `github.ts`.
2. Modify `gh_events.ts` and `types.ts` to incorporate new types.
3. Create a separate project folder within `package.json`.
4. Utilize dependencies such as `date-fns`, `yargs`, `octokit`, `fs`, and `path`.

# How Has This Been Tested?

The refactored scraper can be tested using the following command:

```bash
ts-node src/github.ts org-name data-repo-path date(ex: 2024-06-05) number of days(ex: 2)
```

# Checklist:

- [x] My code adheres to the style guidelines of this project.
- [x] I have conducted a self-review of my code.

2024-06-26 05:56 UTC, rithviknishad requested changes

2024-06-26 05:56 UTC, rithviknishad commented on app/api/leaderboard/functions.ts
> +        return (b.activityData.pr_stale ?? 0) - (a.activityData.pr_stale ?? 0);
Why was this unrelated line changed? Could you specify the issue that's being fixed by this change?

2024-06-26 05:56 UTC, rithviknishad commented on app/feed/page.tsx
> +import { env } from "../../env.mjs";
```suggestion
import { env } from "@/env.mjs";
```

2024-06-26 05:56 UTC, rithviknishad commented on app/feed/page.tsx
> +const GITHUB_ORG: string = env.NEXT_PUBLIC_GITHUB_ORG ?? "";
```suggestion
const GITHUB_ORG: string = env.NEXT_PUBLIC_GITHUB_ORG;
```

2024-06-26 05:56 UTC, rithviknishad commented on components/gh_events/GitHubEvents.tsx
> +    </>
Revert unrelated changes

2024-06-26 05:56 UTC, rithviknishad commented on lib/gh_events.ts
> +  labels: string[] | { name: string }[];
Why was this changed? Let's keep either `string[]` or `{ name: string }[]` only. This could lead to confusion.

2024-06-26 05:56 UTC, rithviknishad commented on lib/gh_events.ts
> +  created_at: Date;
```suggestion
  created_at: string;
```

2024-06-26 05:56 UTC, rithviknishad commented on lib/gh_events.ts
> +  commits_url?: string;
```suggestion
  merged_at: string;
  issue_url: string;
  merged?: boolean;
  commits_url?: string;
```

2024-06-26 05:56 UTC, rithviknishad commented on lib/types.ts
> +  pr_stale?: number;
Could you specify the reason for making this nullable?

```suggestion
  pr_stale: number;
```

2024-06-26 05:56 UTC, rithviknishad commented on lib/types.ts
> +  type: (typeof ACTIVITY_TYPES)[number] | string;
`| string` defeats the point of having strong types on the left.

```suggestion
  type: (typeof ACTIVITY_TYPES)[number];
```

2024-06-26 05:56 UTC, rithviknishad commented on public/logo.png
Why was this added? Seems unrelated to the project.

2024-06-26 05:56 UTC, rithviknishad commented on github.ts
This file does not seem to be used anywhere. Was this accidentally checked-in?

2024-06-26 05:56 UTC, rithviknishad commented on package.json
Scraper is a separate node project. Why was the packages added there also added for the nextjs leaderboard? These new packages added seems to be unused by the nextjs app.

2024-06-26 05:56 UTC, rithviknishad commented on scraper/src/github-scraper/config.ts
> +export const GITHUB_TOKEN = process.env.GITHUB_TOKEN;
`GITHUB_TOKEN` is required only by octokit and octokit is already exported. Why is the `GITHUB_TOKEN` exported too?

```suggestion
const GITHUB_TOKEN = process.env.GITHUB_TOKEN;
```

2024-06-26 05:56 UTC, rithviknishad commented on scraper/src/github-scraper/discussion.ts
> +  }
use `octokit.graphql.paginate` instead of `octokit.graphql`, so that pagination is handled by octokit itself.

2024-06-26 05:56 UTC, rithviknishad commented on scraper/src/github-scraper/fetchEvents.ts
> +  let filteredEvents = [];
```suggestion
  const filteredEvents = [];
```

2024-06-26 05:56 UTC, rithviknishad commented on scraper/src/github-scraper/fetchEvents.ts
> +  console.log("Fetched " + { eventsCount } + " events");
```suggestion
  console.log("Fetched " + { filteredEvents.length } + " events");
```

2024-06-26 05:56 UTC, rithviknishad commented on scraper/src/github-scraper/fetchEvents.ts
> +    ].includes(event.actor.login);
move this blacklist to a global variable, would be better if additional blacklist accounts can be added via comma separated values in env.

2024-06-26 05:56 UTC, rithviknishad commented on scraper/src/github-scraper/fetchEvents.ts
> +    eventsCount++;
```suggestion
```

2024-06-26 05:56 UTC, rithviknishad commented on scraper/src/github-scraper/fetchUserData.ts
> +  let merged_prs = [];
```suggestion
  const merged_prs = [];
```

2024-06-26 05:56 UTC, rithviknishad commented on scraper/src/github-scraper/fetchUserData.ts
> +  });
do a `.map` instead of doing a `.forEach` and `.push`

2024-06-26 05:56 UTC, rithviknishad commented on scraper/src/github-scraper/parseEvents.ts
> +  let emailUserCache: { [key: string]: string } = {};
Are you sure the name and email user cache will work as intended here? Wouldn't the objects be empty everytime the function is called with a new PR event?

2024-06-26 05:56 UTC, rithviknishad commented on scraper/src/github-scraper/types.ts
> +};
Either give a more meaningful name for the type or  inline the type definition in the place where it is used as it is used only in one place and is not re-used elsewhere.

2024-06-26 05:56 UTC, rithviknishad commented on scraper/src/github-scraper/utils.ts
> +  let match: RegExpExecArray | null;
instead of scanning the body, can we directly fetch the linked issues of the PR using graphql?

2024-06-26 05:56 UTC, rithviknishad commented on scraper/src/github-scraper/utils.ts
> +    }
Why was this kept as todo? We are moving to graphql already right?

2024-06-26 05:56 UTC, rithviknishad commented on scraper/src/github-scraper/utils.ts
> +import { promises as fs } from "fs";
```suggestion
import { ... } from "fs/promises";
```

2024-06-26 05:56 UTC, rithviknishad commented on tsconfig.json
> +  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts", "scraper/dist/discssion.js"],
Revert accidental changes

```suggestion
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
```

2024-06-26 05:56 UTC, rithviknishad commented on scraper/src/github-scraper/utils.ts
> +export async function resolve_autonomy_responsibility(
Use proper naming conventins. `snake_case` is used in python. 

```suggestion
export async function resolveAutonomyResponsibility(
```

2024-06-26 16:28 UTC, dgparmar14 commented on github.ts
Yes, Firstly i created whole scraper in one file so i forgot to remove it.

2024-06-28 02:52 UTC, rithviknishad requested changes

2024-06-28 02:52 UTC, rithviknishad commented on scraper/src/github-scraper/utils.ts
> +}
```suggestion
export async function resolveAutonomyResponsibility(
  event: Action,
  user: string,
) {
  return event.event === "cross-referenced" && event.source.type === "issue" && event.source.issue.user.login === user;
}
```

2024-06-28 02:52 UTC, rithviknishad commented on scraper/src/github-scraper/parseEvents.ts
> +const emailUserCache: { [key: string]: string } = {};
Unresolved: https://github.com/coronasafe/leaderboard/pull/458#discussion_r1654071256

2024-06-28 03:41 UTC, rithviknishad requested changes

2024-06-28 03:41 UTC, rithviknishad commented on tests/github-data-schema.test.mjs
> +console.log(filesInDir.length);
```suggestion
```

2024-06-28 05:55 UTC, rithviknishad requested changes

2024-06-28 05:55 UTC, rithviknishad commented on .github/workflows/scraper-dry-run.yaml
NodeJS and PNPM setup step is repeated twice. Avoid duplicating steps.

2024-06-28 05:55 UTC, rithviknishad commented on data/github/discussions/discussions.json
Was this file accidentally checked-in?

2024-06-28 05:55 UTC, rithviknishad commented on public/logo.png
Reviewing again...
Was this file accidentally checked-in?

2024-06-28 05:55 UTC, rithviknishad commented on schemas/discussion-data.yaml
> +  -source
```suggestion
  - source
```

2024-06-28 05:55 UTC, rithviknishad commented on schemas/github-data.yaml
> +  # - discussions
```suggestion
```

2024-06-28 05:55 UTC, rithviknishad commented on schemas/github-data.yaml
> +        isAnswered: boolean
Discussions is in a seaprate file right, why was this added in the github-data schema?

2024-06-28 05:55 UTC, rithviknishad commented on scraper/src/github-scraper/types.ts
> +}
Remove unused interfaces

2024-06-28 05:55 UTC, rithviknishad commented on scraper/src/github-scraper/utils.ts
> +  linkedIssues.push([event.repo.name, `#${linkedIssuesResponse.data.number}`]);
What if the issue was cross-referenced from another repository than the repository of the PR made?

2024-06-28 06:00 UTC, dgparmar14 commented on public/logo.png
Yes, I deleted it already

2024-06-28 11:49 UTC, rithviknishad reviewed
LGTM

2024-07-02 09:57 UTC, dgparmar14 commented
I guess there will be no type errors in the scraper. I checked multiple time if there still let me know.

2024-07-12 10:12 UTC, merged