Added Twitter Link
coronasafe/leaderboard pull request #481
Opened 2024-08-07 12:03 UTC by Indrajeety993648

## Fixes #480 

## Description

This pull request adds the Twitter logo to the relevant components using React Icons. The logo is used for social media links and enhances the visual appeal of the application.

## Changes

- Imported the Twitter logo from `react-icons/bs`.
- Updated the relevant component(s) to include the Twitter logo.

## Motivation and Context

Adding the Twitter logo provides a recognizable icon for linking to Twitter profiles or posts. This integration is part of the effort to improve social media connectivity in the application.

## How Has This Been Tested?

- Verified that the logo appears correctly in the designated components.
- Ensured the responsiveness and visual alignment of the logo on different screen sizes.

## Checklist

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.

## Related Issue

Fixes # 480
## Screenshots 

![Screenshot from 2024-08-07 17-32-14](https://github.com/user-attachments/assets/f6c6ab25-853a-41c1-a236-95b81edf3143)

2024-08-07 12:04 UTC, Indrajeety993648 commented
@rithviknishad  please review  the pull request .

2024-08-07 12:19 UTC, rithviknishad requested changes

2024-08-07 12:19 UTC, rithviknishad commented on components/Footer.tsx
> +                  href={`mailto:${env.NEXT_PUBLIC_TWITTER_URL}`}
Why is the url prefixed with `mailto:`?

2024-08-07 12:19 UTC, rithviknishad commented on components/Footer.tsx
As mentioned in the issue already, make all of the social links optional, and skip rendering it if it is not defined.

2024-08-07 12:19 UTC, rithviknishad commented on components/Footer.tsx
> +                  href={`mailto:${env.NEXT_PUBLIC_TWITTER_URL}`}
This needs to be added to the env schema too

2024-08-07 12:19 UTC, rithviknishad commented on pnpm-lock.yaml
Could you discard the changes to the lockfile?

2024-08-07 18:47 UTC, Indrajeety993648 commented on pnpm-lock.yaml
@rithviknishad sure

2024-08-08 08:57 UTC, rithviknishad commented
Closing as duplicated of #482

2024-08-08 08:57 UTC, closed without merging