added Twitter to connect
coronasafe/leaderboard pull request #490
Opened 2024-08-10 11:58 UTC by Indrajeety993648

##  Add Twitter Support to Footer

## Issue Fixes : #480 

## Description

This pull request introduces support for displaying a Twitter link in the footer component of the application. The following changes have been made:

- **Updated `Footer.tsx` Component:**
  - Added Twitter icon and link to the `Connect` section.
  - Conditionally rendered the Twitter icon based on the presence of `NEXT_PUBLIC_TWITTER_URL` in the environment variables.

- **Updated Environment Configuration (`env.mjs`):**
  - Added `NEXT_PUBLIC_TWITTER_URL` to handle the optional Twitter URL.

- **Fixed Formatting and Style Issues:**
  - Corrected import formatting to comply with Prettier rules.
  - Replaced arbitrary Tailwind CSS values with predefined classes for consistency.

## Changes

### `Footer.tsx`
- Added Twitter support to the `Connect` section.
- Adjusted import statements for improved readability.

### `env.mjs`
- Included `NEXT_PUBLIC_TWITTER_URL` in the environment configuration.

## Checklist
- [x] Code adheres to the project's style guidelines.
- [x] All new and existing tests pass.
- [x] Changes tested locally.

## Testing Instructions
1. Ensure that your `.env` file includes the `NEXT_PUBLIC_TWITTER_URL` variable.
2. Start the development server and verify that the Twitter icon appears in the footer if the URL is provided.
3. Confirm that other social media icons are correctly displayed based on their respective environment variables.

2024-08-10 12:00 UTC, Indrajeety993648 commented
@rithviknishad   please review

2024-08-10 12:23 UTC, rithviknishad requested changes
Could you discard all changes that are unrelated to the related issue?

Feel free to create separate issues for each of the extra things solved.

2024-08-10 14:10 UTC, Indrajeety993648 commented
@rithviknishad  One prettier related problem  that  is necessary  to  solve during commit  that  I changed . Can u review and merge this  PR

2024-08-11 11:09 UTC, Indrajeety993648 commented
@rithviknishad  please review .

2024-08-11 11:47 UTC, rithviknishad requested changes

2024-08-11 11:47 UTC, rithviknishad commented on scraper/pnpm-lock.yaml
Could you discard changes to the lockfile?

2024-08-11 11:47 UTC, rithviknishad commented on env.mjs
> +    NEXT_PUBLIC_TWITTER_URL: process.env.NEXT_PUBLIC_TWITTER_URL, // Add this line
```suggestion
    NEXT_PUBLIC_TWITTER_URL: process.env.NEXT_PUBLIC_TWITTER_URL,
```

2024-08-11 11:47 UTC, rithviknishad commented on env.mjs
> +    NEXT_PUBLIC_TWITTER_URL: z.string().optional(), // Add this line
```suggestion
    NEXT_PUBLIC_TWITTER_URL: z.string().optional(),
```

2024-08-11 11:47 UTC, rithviknishad commented on components/Footer.tsx
> +                    icon={FaTwitter}
You should be using the Twitter's X logo instead

2024-08-11 16:44 UTC, closed without merging