UI enhacements for search, sort and toggle
coronasafe/leaderboard pull request #74
Opened 2022-08-29 16:52 UTC by naman114

Closes #73

The following changes were made:

- Excess spacing between the search bar and live leaderboard is reduced

![image](https://user-images.githubusercontent.com/57593654/187252909-b41fd951-2b24-4e11-b592-ce383424a22c.png)

- Search sort and toggle are placed in a single row in desktop and left justified in mobile view

![image](https://user-images.githubusercontent.com/57593654/187253080-3db4be0f-bcae-4350-a0fe-21bc05e71738.png)

2022-08-30 16:28 UTC, rabilrbl requested changes
**Critical Bug**
![image](https://user-images.githubusercontent.com/63334479/187490053-d46c328f-0fb1-40a0-888f-eddb37e89c27.png)

- As I type my name to search, I hold the "1" badge and Under all categories in "Top Contributors of the week" my name is present.

- The eye button is a bit off.

2022-09-02 15:15 UTC, gigincg commented
@naman114 Can you take care of the changes @rabilrbl requested

2022-09-02 15:28 UTC, naman114 commented
@rabilrbl @gigincg I am not able to replicate the issue on the deploy preview

2022-09-02 16:58 UTC, rabilrbl commented
@naman114 Its firefox related. It looks good on chromium.

2022-09-02 17:36 UTC, naman114 commented
@gigincg @rabilrbl This is weird. What's the cause for this? Can we do anything?

2022-09-02 17:44 UTC, rabilrbl commented
@naman114 Fix https://github.com/naman114/coronasafe-leaderboard/pull/2

2022-09-02 18:14 UTC, rabilrbl approved these changes
LGTM

2022-09-27 04:46 UTC, bodhish approved these changes
LGTM

2022-09-27 04:46 UTC, merged